# Generated by Django 5.2.9 on 2025-12-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
