# Generated by Django 5.2.9 on 2025-12-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productmodel_in_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryModels',
            new_name='CategoryModel',
        ),
    ]
